### ISSUE TITLE
Add a cooking time filter.

### ISSUE THREAD

**Issue by het-patel99** [het-patel99/Recipe_Recommender#7] opened 2021-11-14 21:59 UTC

**Comment by hvudeshi** [comment] 2021-11-27 20:07
Same as the Recipe Rating filter, I have added a cooking time filter too. Have a look at this:
![ss_filters](https://user-images.githubusercontent.com/22682878/143720782-606e3fec-baa4-4248-af79-af5e8c1a40b2.png)


@het-patel99 verify the code again and meanwhile I will try to deploy it on AWS.

**Comment by het-patel99** [comment] 2021-11-27 20:10
Yeah, i will check that in sometime

**Comment by hvudeshi** [comment] 2021-11-28 05:04
It is working on AWS as intended.

**Comment by hvudeshi** [comment] 2021-11-29 22:33
As everything seems working fine, I am closing the issue.

**Closed by hvudeshi** 2021-11-29 22:33 UTC
