### ISSUE TITLE
Add Test Cases for all the columns of the database.

### ISSUE THREAD

**Issue by Vineet2311** [het-patel99/Recipe_Recommender#42] opened 2021-11-29 01:14 UTC

**Comment by Vineet2311** [comment] 2021-11-29 01:19
I have added added all the cases in the test folder, @kalgeekotak99  please verify it.
Path : https://github.com/het-patel99/Recipe_Recommender/tree/master/test

**Comment by het-patel99** [comment] 2021-11-29 22:33
Yes, I can see those test cases, just check that we cover test cases for all the functions. If done then we can close the issue. @kalgeekotak99 just check those test cases!!

**Comment by kalgeekotak99** [comment] 2021-11-29 22:35
Seems fine. You can close this issue for now.

**Comment by hvudeshi** [comment] 2021-11-29 22:40
@Vineet2311 test cases are covering almost everything as intended, and coverage is also increasing, so @Vineet2311 you can close the issue.

**Comment by sal0ni** [comment] 2021-11-29 22:55
Yes it seems fine.

**Closed** 2021-11-29 22:56 UTC
